Add info about creating RPM/DEB packages
Open-CAS/open-cas.github.io pull request #50
Opened 2021-01-28 13:13 UTC by rafalste

Signed-off-by: Rafal Stefanowski <rafal.stefanowski@intel.com>

2021-02-17 09:13 UTC, Deixx requested changes

2021-02-17 09:13 UTC, Deixx commented on pages/open_cas_linux/guide_installing.md
> +You can generate RPM/DEB packages from OpenCAS sources and install them, instead of
Open CAS

2021-02-17 09:17 UTC, Deixx commented on pages/open_cas_linux/guide_installing.md
> +You can generate RPM/DEB packages from OpenCAS sources and install them, instead of
Maybe even Open CAS Linux

2021-02-17 11:07 UTC, rafalste commented on pages/open_cas_linux/guide_installing.md
> +You can generate RPM/DEB packages from OpenCAS sources and install them, instead of
Done

2021-02-18 07:54 UTC, robertbaldyga approved these changes

2021-02-23 14:29 UTC, Deixx approved these changes

2021-03-12 09:32 UTC, Ostrokrzew approved these changes

2021-04-15 08:08 UTC, merged