Update contributing guide
Open-CAS/open-cas.github.io pull request #51
Opened 2021-02-12 10:22 UTC by mmichal10

2021-02-12 10:58 UTC, imjfckm commented on pages/overview/contributing.md
> +**The sequential cutoff policies**
Promotion policies missing

2021-02-12 15:40 UTC, Deixx requested changes

2021-02-12 15:40 UTC, Deixx commented on pages/overview/contributing.md
> +## Naming conventions in the documentation
Maybe add some clarification for devices used.
We have:
- cache
- cache device
- exported object = cache volume (= *colloquially* core...)
- core device = backend device = core? 😮

Should core (by itself) exist in documentation?

2021-02-16 12:57 UTC, robertbaldyga submitted a review, later dismissed

2021-02-16 13:55 UTC, robertbaldyga approved these changes

2021-02-17 09:09 UTC, Deixx approved these changes

2021-02-17 09:18 UTC, Deixx commented on pages/overview/contributing.md
> +* Open CAS
I was looking into some older documentation and 'Open CAS Linux' was used there

2021-02-17 09:24 UTC, Deixx submitted a review, later dismissed

2021-02-17 09:38 UTC, rafalste approved these changes

2021-02-17 11:08 UTC, rafalste approved these changes

2021-02-17 12:36 UTC, katlapinka approved these changes

2021-02-18 07:52 UTC, merged